app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view())
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path(패턴, 매핑) /blog/
    # path("", views.index), # FBV
    # 글 목록 조회
    path("", views.List.as_view(), name='list'), # /blog/
    # 글 상세 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'), # /blog/detail/1
    # 글 작성
    path("write/", views.Write.as_view(), name='write'), # /blog/write/
    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # 코멘트 작성
    path("detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name='cm-write'),
    # 코멘트 삭제
    path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
    # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    # 태그 삭제
    path("detail/<int:pk>/hashtag/delete/", views.HashTagDelete.as_view(), name='tag-delete'),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Comment on {self.post.title}'


class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    
    def __str__(self):
        return self.name

blog/forms.py
# blog/forms.py
from django import forms
from .models import Post, Comment, HashTag

# Form: html에 있는 form 태그
# Model Form: model을 사용하는 form
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': '3', 'cols':'35'})
        }


class HashTagForm(forms.ModelForm):
    
    class Meta:
        model = HashTag
        fields = ['name']

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Post, Comment, HashTag
from .forms import PostForm, CommentForm, HashTagForm
from django.urls import reverse_lazy, reverse

# Create your views here.
# def index(request):
#     if request.method == 'GET':
#         return HttpResponse('Index page GET')
#     # 나머지 요청
#     # 에러, 예외처리
#     return HttpResponse('No!!!')

### Post
class Index(View):
    def get(self, request):
        # return HttpResponse('Index page GET class')
        
        # 데이터베이스에 접근해서 값을 가져와야 합니다.
        # 게시판에 글들을 보여줘야하기 때문에 데이터베이스에서 "값 조회"
        # MyModel.objects.all()
        post_objs = Post.objects.all()
        # context = 데이터베이스에서 가져온 값
        context = {
            "posts": post_objs
        }
        # print(post_objs) QuerySet<[post 1, 2, 3, 4, 5]>
        return render(request, 'blog/board.html', context)


# write
# post - form
# 글 작성 화면
def write(request):
    if request.method == 'POST':
        # form 확인
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('blog:list')

    form = PostForm()
    return render(request, 'blog/post_form.html', { 'form': form })


# Django 자체의 클래스 뷰 기능도 강력, 편리
# model, template_name, context_object_name,
# paginate_by, form_class, form_valid(), get_queryset()
# django.views.generic -> ListView
class List(ListView):
    model = Post # 모델
    template_name = 'blog/post_list.html' # 템플릿
    context_object_name = 'posts' # 변수 값의 이름


class Write(CreateView):
    model = Post # 모델
    form_class = PostForm # 폼
    success_url = reverse_lazy('blog:list') # 성공시 보내줄 url


class Detail(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'


class Update(UpdateView):
    model = Post
    template_name = 'blog/post_edit.html'
    fields = ['title', 'content']
    # success_url = reverse_lazy('blog:list')
    
    # intial 기능 사용 -> form에 값을 미리 넣어주기 위해서
    def get_initial(self):
        initial = super().get_initial() # UpdateView(generic view)에서 제공하는 initial(딕셔너리)
        post = self.get_object() # pk 기반으로 객체를 가져옴
        initial['title'] = post.title
        initial['content'] = post.content
        return initial
    
    def get_success_url(self): # get_absolute_url
        post = self.get_object() # pk 기반으로 현재 객체 가져오기
        return reverse('blog:detail', kwargs={ 'pk': post.pk })


class Delete(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list')


class DetailView(View):
    def get(self, request, pk): # post_id: 데이터베이스 post_id
        # list -> object 상세 페이지 -> 상세 페이지 하나의 내용
        # pk 값을 왔다갔다, 하나의 인자
        
        # 데이터베이스 방문
        # 해당 글
        # 장고 ORM (pk: 무조건 pk로 작성해야한다.)
        post = Post.objects.get(pk=pk)
        # 댓글
        comments = Comment.objects.filter(post=post)
        # 해시태그
        hashtags = HashTag.objects.filter(post=post)
        
        # 댓글 Form
        comment_form = CommentForm()
        
        # 태그 Form
        hashtag_form = HashTagForm()
        
        context = {
            'post': post,
            'comments': comments,
            'hashtags': hashtags,
            'comment_form': comment_form,
            'hashtag_form': hashtag_form
        }
        
        return render(request, 'blog/post_detail.html', context)


### Comment
class CommentWrite(View):
    # def get(self, request):
    #     pass
    def post(self, request, pk):
        form = CommentForm(request.POST)
        if form.is_valid():
            # 사용자에게 댓글 내용을 받아옴
            content = form.cleaned_data['content']
            # 해당 아이디에 해당하는 글 불러옴
            post = Post.objects.get(pk=pk)
            # 댓글 객체 생성, create 메서드를 사용할 때는 save 필요 없음
            comment = Comment.objects.create(post=post, content=content)
            # comment = Comment(post=post) -> comment.save()
            return redirect('blog:detail', pk=pk)


class CommentDelete(View):
    def post(self, request, pk):
        # 지울 객체를 찾아야 한다. -> 댓글 객체
        comment = Comment.objects.get(pk=pk)
        # 상세페이지로 돌아가기
        post_id = comment.post.id
        # 삭제
        comment.delete()
        
        return redirect('blog:detail', pk=post_id)


### Tag
class HashTagWrite(View):
    def post(self, request, pk):
        form = HashTagForm(request.POST)
        if form.is_valid():
            # 사용자에게 태그 내용을 받아옴
            name = form.cleaned_data['name']
            # 해당 아이디에 해당하는 글 불러옴
            post = Post.objects.get(pk=pk)
            # 댓글 객체 생성, create 메서드를 사용할 때는 save 필요 없음
            hashtag = HashTag.objects.create(post=post, name=name)
            # comment = Comment(post=post) -> comment.save()
            return redirect('blog:detail', pk=pk)


class HashTagDelete(View):
    def post(self, request, pk):
        # 지울 객체를 찾아야 한다. -> 태그 객체
        hashtag = HashTag.objects.get(pk=pk)
        # 상세페이지로 돌아가기
        post_id = hashtag.post.id
        # 삭제
        hashtag.delete()
        
        return redirect('blog:detail', pk=post_id)

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>블로그</title>
  </head>
  <body>
    <div class="container">
      {% block content %} 
      {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/board.html
{% extends 'blog/base.html' %} 

{% block content %}
    <h1>블로그 게시판 화면</h1>
    <p>블로그 게시판 첫 화면입니다.</p>
    <a href="{% url 'blog:write' %}">글 작성</a>
    <!-- 글이 있을 때 -->
    <!-- 테이블 -->

    <!-- 조건문 -->
    {% if posts %}
        <table>
            <thead>
                <tr>
                    <td>Title</td>
                    <td>Content</td>
                    <td>Writer</td>
                </tr>
            </thead>
            {% for post in posts %}
            <tr>
                <td>{{ post.title }}</td>
                <td>{{ post.content }}</td>
                <td>{{ post.writer }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>작성된 게시물이 없습니다</p>
    {% endif %}

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>제목: {{ post.title }}</h2>
<a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
<form action="{% url 'blog:delete' pk=post.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="삭제" class="btn">
</form>
<p>내용: {{ post.content }}</p>
<p>작성자: {{ post.writer }}</p>
<p>작성일: {{ post.created_at }}</p>
<hr>

<!-- 작성 화면 -->
<h3>댓글</h3>
<form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
    {% csrf_token %}
    {{ comment_form.content }}
    <input type="submit" value="댓글 작성">
</form>
<br>
<!-- comments -->
<!-- if 문 -->
{% if comments %}
    <!-- for 문 -->
    <ul>
        {% for comment in comments %}
        <!-- 내용, 작성시간, 삭제 버튼 -->
            <li>{{ comment.content }} / {{ comment.created_at }}
                <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="X" class='btn'>
                </form>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>댓글이 없습니다.</p>
{% endif %}
<hr>
<!-- 태그작성 화면 -->
<h3>해시태그</h3>
<form action="{% url 'blog:tag-write' pk=post.pk %}" method="post">
    {% csrf_token %}
    {{ hashtag_form.name }}
    <input type="submit" value="태그 작성">
</form>
{% if hashtags %}
<ul>
    {% for hashtag in hashtags %}
    <li>
        {{ hashtag }}
        <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="X" class='btn'>
        </form>
    </li>
    {% endfor %}
</ul>
{% else %}
<br>
<p>해시태그가 없습니다.</p>
{% endif %}

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.title.label_tag }}
    <input type="text" name="{{ form.title.name }}" value="{{ form.initial.title }}">
    <br>
    {{ form.content.label_tag }}
    <textarea type="text" name="{{ form.content.name }}">{{ form.initial.content }}</textarea>
    <br>
    <input type="submit" value="수정 완료">
</form>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <p>블로그 글 작성 화면</p>
    <!-- 제목 -->
    <!-- 내용 -->
    <form action="{% url 'blog:write' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-outline-success">
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <p>블로그 게시판 첫 화면입니다.</p>
    <a href="{% url 'blog:write' %}" class="btn btn-outline-success">글 작성</a>
    <!-- 조건문 -->
    <!-- 글이 있을 때: 테이블 출력 -->
    {% if posts %}
        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <td>제목</td>
                    <td>내용</td>
                    <td>작성자</td>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.title }}</a></td>
                        <td>{{ post.writer }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <!-- 글이 없을 때: 문구 출력 -->
        <p>작성된 게시물이 없습니다.</p>
    {% endif %}
 
{% endblock %}

blog/templates/blog/write.html
{% extends 'blog/base.html' %} 

{% block content %}
  <h1>블로그 글 작성 화면</h1>
  <!-- 제목 -->
  <!-- 내용 -->
  <form action="{% url 'blog:write' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
{% endblock %}